### ISSUE TITLE
Oauth

### ISSUE THREAD

**Issue by saroar** [avielmenter/seriatim-server#1]
Hi there Can you help me to implement OAuth into Actix-Web API base app, please 
I like to my have email res.. base + OAuth

thanks

**Comment by avielmenter** [comment]
I've never used Actix (this is built using Rocket), and barely have time to maintain this application while I'm in law school. 

That said, feel free to use the code in the OAuth folder if you find it helpful. Nothing outside of mod.rs is Rocket specific.

**Comment by saroar** [comment]
thanks for the reply :) are programmer or lawyer just for interest:)
